(() => {
  "use strict";

  const EM = window.EM;

  EM.ITEMS = {
    wood: "Treverk",
    stone: "Stein",
    ore: "Jernmalm",
    metal: "Metall",
    coal: "Kull",
    scrap: "Skrapmetall",
    cloth: "Tøy",
    food: "Mat",
    dirtyWater: "Skittent vann",
    water: "Rent vann",
    herbs: "Urter",
    ammo: "Ammunisjon",
    arrows: "Piler",
    parts: "Deler",
    bandage: "Bandasje",
    medkit: "Førstehjelpspakke",
    canteen: "Feltflaske",
  };

  EM.WEAPONS = {
    knife: {
      name: "Kniv",
      type: "melee",
      damage: 16,
      range: 42,
      cooldown: 0.42,
      noise: 40,
      stamina: 5,
    },
    axe: {
      name: "Øks",
      type: "melee",
      damage: 32,
      range: 50,
      cooldown: 0.62,
      noise: 80,
      stamina: 10,
    },
    pickaxe: {
      name: "Hakke",
      type: "melee",
      damage: 28,
      range: 48,
      cooldown: 0.72,
      noise: 95,
      stamina: 12,
    },
    spear: {
      name: "Spyd",
      type: "melee",
      damage: 36,
      range: 68,
      cooldown: 0.72,
      noise: 60,
      stamina: 11,
    },
    bow: {
      name: "Bue",
      type: "projectile",
      damage: 42,
      range: 520,
      speed: 560,
      cooldown: 0.68,
      noise: 75,
      ammo: "arrows",
    },
    pistol: {
      name: "Pistol",
      type: "projectile",
      damage: 48,
      range: 640,
      speed: 820,
      cooldown: 0.32,
      noise: 360,
      ammo: "ammo",
    },
    shotgun: {
      name: "Hagle",
      type: "spread",
      damage: 30,
      pellets: 6,
      range: 380,
      speed: 720,
      cooldown: 0.92,
      noise: 520,
      ammo: "ammo",
    },
  };

  EM.BUILDINGS = {
    campfire: {
      name: "Bål",
      hp: 120,
      w: 42,
      h: 42,
      color: "#e76f28",
      light: 260,
      warmth: 120,
      station: true,
      repair: { wood: 1, stone: 1 },
    },
    workbench: {
      name: "Arbeidsbenk",
      hp: 180,
      w: 62,
      h: 42,
      color: "#8b5e34",
      station: true,
      repair: { wood: 2, scrap: 1 },
    },
    smelter: {
      name: "Smelter",
      hp: 240,
      w: 58,
      h: 58,
      color: "#59656a",
      light: 210,
      warmth: 80,
      station: true,
      repair: { stone: 2, scrap: 1 },
    },
    woodWall: {
      name: "Trevegg",
      hp: 190,
      w: 56,
      h: 26,
      color: "#72502f",
      solid: true,
      repair: { wood: 2 },
    },
    stoneWall: {
      name: "Steinvegg",
      hp: 360,
      w: 58,
      h: 30,
      color: "#7d8587",
      solid: true,
      repair: { stone: 2 },
    },
    spikes: {
      name: "Piggfelle",
      hp: 110,
      w: 48,
      h: 48,
      color: "#a07a48",
      trap: true,
      repair: { wood: 1, stone: 1 },
    },
    rainCollector: {
      name: "Regnsamler",
      hp: 140,
      w: 46,
      h: 46,
      color: "#6d93a4",
      waterStore: 0,
      repair: { wood: 1, cloth: 1 },
    },
    torch: {
      name: "Fakkel",
      hp: 55,
      w: 22,
      h: 22,
      color: "#ffb347",
      light: 300,
      warmth: 70,
      repair: { wood: 1, cloth: 1 },
    },
    bedroll: {
      name: "Sovepose",
      hp: 80,
      w: 56,
      h: 32,
      color: "#36527a",
      repair: { cloth: 1 },
    },
    storage: {
      name: "Lagerkasse",
      hp: 120,
      w: 46,
      h: 38,
      color: "#8b6a3d",
      repair: { wood: 1 },
    },
  };

  EM.NODE_DEFS = {
    tree: {
      name: "Tre",
      hp: 5,
      color: "#245c36",
      needs: null,
      noise: 130,
    },
    rock: {
      name: "Stor stein",
      hp: 7,
      color: "#737d80",
      needs: null,
      noise: 170,
    },
    oreRock: {
      name: "Malmstein",
      hp: 9,
      color: "#586165",
      needs: "pickaxe",
      noise: 190,
    },
    puddle: {
      name: "Vannpytt",
      hp: 1,
      color: "#236d88",
      needs: null,
      noise: 35,
    },
    bush: {
      name: "Bærbusk",
      hp: 2,
      color: "#357a45",
      needs: null,
      noise: 45,
    },
    scrapPile: {
      name: "Skrothaug",
      hp: 4,
      color: "#82745e",
      needs: null,
      noise: 120,
    },
  };

  EM.ZOMBIE_DEFS = {
    walker: {
      name: "Vandrer",
      hp: 56,
      speed: 56,
      damage: 8,
      radius: 15,
      sense: 235,
      color: "#6e8f62",
      attackCooldown: 1.0,
    },
    runner: {
      name: "Løper",
      hp: 38,
      speed: 102,
      damage: 7,
      radius: 14,
      sense: 285,
      color: "#8f9160",
      attackCooldown: 0.72,
    },
    brute: {
      name: "Kjempe",
      hp: 160,
      speed: 42,
      damage: 20,
      radius: 22,
      sense: 230,
      color: "#65705f",
      attackCooldown: 1.25,
    },
    spitter: {
      name: "Spytter",
      hp: 70,
      speed: 50,
      damage: 6,
      radius: 16,
      sense: 310,
      color: "#73996f",
      attackCooldown: 1.4,
    },
  };

  EM.RECIPES = [
    { id: "axe", name: "Lag øks", category: "Verktøy", cost: { wood: 4, stone: 3, cloth: 1 }, weapon: "axe", station: null, desc: "Gir mer tre fra trær og fungerer som våpen." },
    { id: "pickaxe", name: "Lag hakke", category: "Verktøy", cost: { wood: 4, stone: 5, cloth: 1 }, weapon: "pickaxe", station: null, desc: "Kreves for effektiv gruvedrift og malm." },
    { id: "spear", name: "Lag spyd", category: "Våpen", cost: { wood: 5, stone: 2, cloth: 1 }, weapon: "spear", station: null, desc: "Lengre rekkevidde i nærkamp." },
    { id: "bandage", name: "Lag 2 bandasjer", category: "Medisin", cost: { cloth: 3, herbs: 1 }, item: "bandage", amount: 2, station: null, desc: "Trygg tidlig healing." },
    { id: "arrows", name: "Lag 10 piler", category: "Ammo", cost: { wood: 3, stone: 1 }, item: "arrows", amount: 10, station: null, desc: "Ammunisjon til bue." },

    { id: "campfire", name: "Bygg bål", category: "Bygg", cost: { wood: 6, stone: 4 }, build: "campfire", station: null, desc: "Gir faktisk lys, renser vann og lager kull." },
    { id: "workbench", name: "Bygg arbeidsbenk", category: "Bygg", cost: { wood: 12, scrap: 6 }, build: "workbench", station: null, desc: "Låser opp flere oppskrifter." },
    { id: "woodWall", name: "Bygg trevegg", category: "Bygg", cost: { wood: 5 }, build: "woodWall", station: null, desc: "Billig baseforsvar. R roterer før plassering." },
    { id: "spikes", name: "Bygg piggfelle", category: "Bygg", cost: { wood: 7, stone: 3 }, build: "spikes", station: null, desc: "Skader zombier og mister holdbarhet." },

    { id: "bow", name: "Lag bue", category: "Våpen", cost: { wood: 8, cloth: 4 }, weapon: "bow", station: "workbench", desc: "Stille avstandsvåpen." },
    { id: "canteen", name: "Lag feltflaske", category: "Utstyr", cost: { scrap: 3, cloth: 2 }, item: "canteen", amount: 1, station: "workbench", desc: "Samler mer vann fra pytter." },
    { id: "rainCollector", name: "Bygg regnsamler", category: "Bygg", cost: { wood: 8, cloth: 4, scrap: 3 }, build: "rainCollector", station: "workbench", desc: "Produserer rent vann over tid." },
    { id: "torch", name: "Bygg fakkel", category: "Bygg", cost: { wood: 2, cloth: 1 }, build: "torch", station: "workbench", desc: "Gir mye lys i mørket." },
    { id: "bedroll", name: "Bygg sovepose", category: "Bygg", cost: { cloth: 6, wood: 2 }, build: "bedroll", station: "workbench", desc: "Setter respawnpunkt." },
    { id: "storage", name: "Bygg lagerkasse", category: "Bygg", cost: { wood: 10, scrap: 2 }, build: "storage", station: "workbench", desc: "Baseobjekt og fremtidig lagring." },
    { id: "smelter", name: "Bygg smelter", category: "Bygg", cost: { stone: 14, scrap: 6, wood: 6 }, build: "smelter", station: "workbench", desc: "Smelter jernmalm til metall og gir lys." },

    { id: "stoneWall", name: "Bygg steinvegg", category: "Bygg", cost: { stone: 10, metal: 1 }, build: "stoneWall", station: "smelter", desc: "Sterkere baseforsvar. R roterer." },
    { id: "pistol", name: "Reparer pistol", category: "Våpen", cost: { scrap: 14, parts: 4, metal: 2 }, weapon: "pistol", station: "workbench", desc: "Bråkete, men effektiv." },
    { id: "shotgun", name: "Bygg hagle", category: "Våpen", cost: { scrap: 22, parts: 8, wood: 6, metal: 4 }, weapon: "shotgun", station: "smelter", desc: "Kraftig baseforsvar." },
  ];

  EM.REFINING = [
    { id: "charcoal", name: "Brenn treverk til kull", station: "campfire", cost: { wood: 2 }, output: { coal: 1 }, time: 4 },
    { id: "cleanWater", name: "Rens skittent vann", station: "campfire", cost: { dirtyWater: 1, wood: 1 }, output: { water: 1 }, time: 3 },
    { id: "smeltIron", name: "Smelt jernmalm til metall", station: "smelter", cost: { ore: 2, coal: 1 }, output: { metal: 1 }, time: 5 },
    { id: "ammo", name: "Press 12 patroner", station: "smelter", cost: { scrap: 5, metal: 1 }, output: { ammo: 12 }, time: 4 },
  ];
})();
